UploadFileProject/Controllers/GallaryController.cs
using Microsoft.AspNetCore.Mvc;

namespace UploadFileProject.Controllers
{
    public class GallaryController : Controller
    {

        private readonly string wwwrootDirectory =
            Path.Combine(Directory.GetCurrentDirectory(), "Filles");
        [HttpGet]
        public IActionResult Index()
        {
            /*List<string> images = Path.GetFiles(wwwrootDirectory, "*.png")
                .Select(Path.GetFileName)
                .ToList();*/
            return View();
        }
            [HttpPost]
            public async Task<IActionResult> IndexAsync(IFormFile myFile)

            {
                if (myFile != null)
                {
                    var path = Path.Combine(
                        wwwrootDirectory,
                        DateTime.Now.Ticks.ToString() + Path.GetExtension(myFile.FileName));
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await myFile.CopyToAsync(stream);
                    }
                }
                return View();
            }

        }
    }

UploadFileProject/Controllers/HomeController.cs
//using Microsoft.AspNetCore.Mvc;
//using System.Data.SqlClient;
//using System.Diagnostics;
//using UploadFileProject.Models;

//namespace UploadFileProject.Controllers
//{
//    static string constr =
//    public IActionResult Index()
//    {
//        return View(PopulateFiles());
//    }

//    [HttpPost]
//    public IActionResult Index(List<IFormFile> postedFiles)
//    {
//        foreach (IFormFile postedFilein postedFiles)
//        {
//            string fileName = Path.GetFileName(postedFile.FileName);
//            string type = postedFile.ContentType;
//            byte[] bytes = null;
//            using (MemoryStream ms = new MemoryStream())
//            {
//                postedFile.CopyTo(ms);
//                bytes = ms.ToArray();
//            }
//            using (SqlConnection con = new SqlConnection(constr))
//            {
//                using (SqlCommand cmd = new SqlCommand())
//                {
//                    cmd.CommandText = "INSERT INTO tblFiles(Name, ContentType, Data) VALUES (@Name, @ContentType, @Data)";
//                    cmd.Parameters.AddWithValue("@Name", fileName);
//                    cmd.Parameters.AddWithValue("@ContentType", type);
//                    cmd.Parameters.AddWithValue("@Data", bytes);
//                    cmd.Connection = con;
//                    con.Open();
//                    cmd.ExecuteNonQuery();
//                    con.Close();
//                }
//            }
//        }

//        return View(PopulateFiles());
//    }

//    public FileResult DownloadFile(int fileId)
//    {
//        FileModel model = PopulateFiles().Find(x => x.Id == Convert.ToInt32(fileId));
//        string fileName = model.Name;
//        string contentType = model.ContentType;
//        byte[] bytes = model.Data;
//        return File(bytes, contentType, fileName);
//    }

//    private static List<FileModel> PopulateFiles()
//    {
//        List<FileModel> files = new List<FileModel>();
//        using (SqlConnection con = new SqlConnection(constr))
//        {
//            string query = "SELECT * FROM tblFiles";
//            using (SqlCommand cmd = new SqlCommand(query))
//            {
//                cmd.Connection = con;
//                con.Open();
//                using (SqlDataReader sdr = cmd.ExecuteReader())
//                {
//                    while (sdr.Read())
//                    {
//                        files.Add(new FileModel
//                        {
//                            Id = Convert.ToInt32(sdr["Id"]),
//                            Name = sdr["Name"].ToString(),
//                            ContentType = sdr["ContentType"].ToString(),
//                            Data = (byte[])sdr["Data"]
//                        });
//                    }
//                }
//                con.Close();
//            }
//        }

//        return files;
//    }
//}

UploadFileProject/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
@model List<string>
<div class="container">
    <div class="row">
        @foreach (var images in Model)
        {
            <div class="col-md-3">
                <div class="alert alert-success" role="alert">
                    <img src="~/@images" alt="Alternate Text" height="100px" width="205px" />
                </div>
            </div>

        }
    </div>

    <div class="container">
        @using (Html.BeginForm("Index", "Gallary", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="form-group col-md-6">
                    <input type="file" class="form-control" name="myFile" />
                </div>
                <div class="form-group col-md-6">
                    <input type="submit" class="filesubmit" name="upload" value="upload" />
                </div>
            </div>

        }
    </div>
</div>