UploadFileProject/Controllers/Home2Controller.cs
using UploadFileProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using UploadFileProject.BusinessLogic_bl;

namespace UploadFileProject.Controllers
{
    public class Home2Controller : Controller
    {
        static string constr = @"Data source=MANASA;user id=sa;password=123456;initial catalog=MANASA";
        public IActionResult Index()
        {
            return View(PopulateFiles());
        }

        [HttpPost]
        public IActionResult Index(List<IFormFile?> postedFiles)
        {
            foreach (IFormFile postedFile in postedFiles)
            {
                string fileName = Path.GetFileName(postedFile.FileName);
                string type = postedFile.ContentType;
                byte[] bytes = null;
                using (MemoryStream ms = new MemoryStream())
                {
                    postedFile.CopyTo(ms);
                    bytes = ms.ToArray();
                }
                using (SqlConnection con = new SqlConnection(constr))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.CommandText = "INSERT INTO Files(Name, ContentType, Data) VALUES (@Name, @ContentType, @Data)";
                        cmd.Parameters.AddWithValue("@Name", fileName);
                        cmd.Parameters.AddWithValue("@ContentType", type);
                        cmd.Parameters.AddWithValue("@Data", bytes);
                        cmd.Connection = con;
                        con.Open();
                        cmd.ExecuteNonQuery();
                        con.Close();
                    }
                }
            }

            return View(PopulateFiles());
        }

        public FileResult DownloadFile(int fileId)
        {
            FileModel model = PopulateFiles().Find(x => x.Id == Convert.ToInt32(fileId));
            string fileName = model.Name;
            string contentType = model.ContentType;
            byte[] bytes = model.Data;
            return File(bytes, contentType, fileName);
        }

        private static List<FileModel> PopulateFiles()
        {
            List<FileModel> files = new List<FileModel>();
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "SELECT * FROM Files";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            files.Add(new FileModel
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                Name = sdr["Name"].ToString(),
                                ContentType = sdr["ContentType"].ToString(),
                                Data = (byte[])sdr["Data"]
                            });
                        }
                    }
                    con.Close();
                }
            }

            return files;
        }
        public IActionResult DELETE(int? Id)
        {
            bool res = Delete_bi.Delete((int)Id);
            if (res == true)
            {
                return RedirectToAction("Index");
            }
            else
            {

                return View();
            }
            
        }
        public IActionResult Forgetpassword()
        {
            return View();
        }
    }

    
        
        
}

UploadFileProject/Views/Home2/Index.cshtml
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@using UploadFileProject.Models
@model List<FileModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <style>
        table, td, th {
            border: 1px solid black;
        }

        table {
            border-collapse: collapse;
            width: 75%;
        }

        th {
            height: 70px;
        }

        h1 {
            text-align: center;
        }
    </style>
</head>
<body>
    <form asp-action="Index" asp-controller="Home2" method="post" enctype="multipart/form-data">
        <centre><h1>*File Upload*</h1></centre>
        <h1 style="background-color:powderblue; accent-color" Select File</h1>
        <input type="file" name="postedFiles" multiple />
        <input type="submit" value="Upload" />
    </form>
    <hr />
    <table cellpadding="0" cellspacing="0" class="table">

        <tr>
           
                <th scope="col">File Name</th>
                <th scope="col">Download</th>
                <th scope="col">Delete</th>
            
        </tr>
        @foreach (FileModel file in Model)
        {
            <tr>
                <td>@file.Name</td>

                <td><a href='@Url.Action("DownloadFile","Home2", new { fileId = file.Id })'>Download</a></td>
                <td>@Html.ActionLink("Delete","DELETE","Home2", new {Id =file.Id},  new { onclick = "return confirm('Are sure wants to delete?');" })</td>

            </tr>
        }
    </table>
</body>
</html>